# ML Lab 1

### 1. Convert a 1-D array into a 2-D array with 3 rows.

In [3]:
import numpy as np
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. Replace all odd numbers in the given array with -1

In [4]:
b=np.arange(10)
print(b)
b[b %2 !=0] =-1
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 3. Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [5]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


### 4. Extract the first four columns of this 2-D array.

In [8]:
Assign = np.arange(100).reshape(5,-1) 
Assign[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

## Additional questions

### 1. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [10]:
x = np.random.randint(10, 30, 10)
x

array([11, 18, 21, 27, 14, 23, 14, 24, 16, 25])

### 2. Consider the following matrices :
#### A=((1,2,3),(4,5,6),(7,8,10))and B=((7,8,10),(4,5,6),(1,2,3))
#### Write a python program to perform the following using Numeric Python (numpy).
#### i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
#### ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C 
#### iii) Product of two matrices A and B, and print the resultant matrix D
#### iv) Sort the elements of resultant matrix C and print the resultant Matrix E.
#### v) Transpose the Matrix E and print the result

In [16]:
A= np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 10]])

B= np.array([[7, 8, 10],
            [4, 5, 6], 
            [1, 2, 3]]) 

C = A+B
E = A-B

C,E

(array([[ 8, 10, 13],
        [ 8, 10, 12],
        [ 8, 10, 13]]),
 array([[-6, -6, -7],
        [ 0,  0,  0],
        [ 6,  6,  7]]))

In [18]:
print("Sum of all elements in A: ", A.sum())
print("Sum of all the columns of matrix B: ", B.sum(axis = 0))
print("Sum of all the rows of matrix C: ", C.sum(axis = 1))

Sum of all elements in A:  46
Sum of all the columns of matrix B:  [12 15 19]
Sum of all the rows of matrix C:  [31 30 31]


In [19]:
A@B

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [20]:
E.transpose()

array([[-6,  0,  6],
       [-6,  0,  6],
       [-7,  0,  7]])